version: "3"

services:
  ui:
    container_name: ui
    restart: always
    build: ./ui
    env_file:
      - ./ui/.env
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    container_name: api
    restart: always
    build: ./api
    env_file:
      - ./api/.env
    ports:
        - "4002:4002"
    depends_on:
        - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
        - ./mongo:/data/db
    ports:
        - "27017:27017"
