export { default as signup } from './signup.route'
export { default as login } from './login.route'
export { default as saveWeight } from './save-weight.route'
export { default as getWeight } from './get-weight.route'
export { default as updateWeight } from './update-weight.route'
export { default as deleteWeight } from './delete-weight.route'
